#server:
#  port: 8080 #eureka 的默认端口
#spring:
#  application:
#    name: eureka-client-a #应用名称
#
#eureka:
#  client:
#    service-url:  #指定注册地址
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true #可以不往eureka 服务上注册
#    fetch-registry: true  #是否拉去服务列表
#    registry-fetch-interval-seconds: 10 #为了解决服务器列表脏读问题 10s拉取一次
#
#  instance:
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    hostname: localhost #主机名称 或者服务ip
#    prefer-ip-address: true #以ip的形式显示具体的服务信息
#    lease-renewal-interval-in-seconds: 10    #服务实例的续约时间间隔
#单机版


server:
  port: 8080 #eureka 的默认端口
spring:
  application:
    name: eureka-client-a #应用名称

eureka:
  client:
    service-url:  #指定注册地址
      defaultZone: http://peer1:8761/eureka
    register-with-eureka: true #可以不往eureka 服务上注册
    fetch-registry: true  #是否拉去服务列表
    registry-fetch-interval-seconds: 10 #为了解决服务器列表脏读问题 10s拉取一次

  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: localhost #主机名称 或者服务ip
    prefer-ip-address: true #以ip的形式显示具体的服务信息
    lease-renewal-interval-in-seconds: 10    #服务实例的续约时间间隔

